env:
  browser: true
  es2021: true
extends:
  - 'airbnb'
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: 'module'
plugins:
  - 'react'
rules: {
  linebreak-style: ['warn', 'windows'],
  react/jsx-filename-extension: [1, { extensions: ['.js', '.jsx'] }],
  semi: [2, 'always'],
  comma-dangle: ['warn', 'never'],
  no-underscore-dangle: ['warn', { allow: ['__REDUX_DEVTOOLS_EXTENSION__'] }],
  arrow-body-style: ['warn', 'as-needed'],
  react/prop-types: 0,
  import/prefer-default-export: 0,
  react/react-in-jsx-scope: 0
}
settings: {
  react: {
    version: 'detect'
  }
}
