env:
  browser: true
  es2021: true
extends:
  - 'airbnb'
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: 'module'
plugins:
  - 'react'
rules: {
  linebreak-style: ["error", "windows"],
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }],
  comma-dangle: ["error", "never"],
  react/prop-types: 0,
  jsx-a11y/label-has-associated-control: ["error", {
        "required": {
          "some": ["nesting", "id"]
        }
      }],
  no-param-reassign: ["error", { "props": false }]
}
settings: {
  react: {
    version: 'detect'
  }
}
