env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules: {
  linebreak-style: ['error', 'windows'],
  import/no-unresolved: 'off',
  comma-dangle: ['error', 'never'],
  arrow-parens: ['error', 'as-needed'],
  object-curly-newline: ['error', { 'consistent': true }],
  consistent-return: 0,
  implicit-arrow-linebreak: 0,
  arrow-body-style: ['error', 'as-needed'],
  no-console: 0,
  prefer-const: ['error', { 'destructuring': 'all' }],
  func-names: ['error', 'never'],
  class-methods-use-this: 0
}
